[build-system]
requires = ["setuptools", "wheel", "numpy<2.0", "setuptools_scm[toml]", "pybind11>=2.11.0"]

[tool.black]
line-length = 79
skip-string-normalization = true

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "node-and-date"
