python:
  - 3.9
  - 3.10
  - 3.11
c_compiler:
  - gcc                    # [linux]
  - clang                  # [osx]
  - vs2019                 # [win]
cxx_compiler:
  - gxx                    # [linux]
  - clangxx                # [osx]
  - vs2019                 # [win]
cxx_compiler_version:      # [osx]
  - 16                     # [osx]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 11.0                   # [osx]
target_platform:
  - linux-64               # [linux]
  - osx-64                 # [osx]
  - osx-arm64              # [osx]
  - win-64                 # [win]
